export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";

//Authentication
export const LOGIN = "LOGIN";
export const SIGN_UP = "SIGN_UP";

export const UPDATE_HOME = "UPDATE_HOME";
export const GET_HOME = "GET_HOME";

export const UPDATE_SHOP = "UPDATE_SHOP";
export const GET_SHOP = "GET_SHOP";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_BLOG = "GET_BLOG";
export const GET_ALL_BLOG = "GET_ALL_BLOG";
export const GET_BLOG_BY_TAG = "GET_BLOG_BY_TAG";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";

export const GET_KEYWORD = "GET_KEYWORD";

export const GET_BANNER = "GET_BANNER";
export const ADD_BANNER = "ADD_BANNER";
export const UPDATE_BANNER = "UPDATE_BANNER";
export const DELETE_BANNER = "DELETE_BANNER";

export const ADD_LEARN = "ADD_LEARN";
export const EDIT_LEARN = "EDIT_LEARN";
export const DELETE_LEARN = "DELETE_LEARN";
export const GET_LEARN = "GET_LEARN";
export const ADD_SUB_LEARN = "ADD_SUB_LEARN";
export const EDIT_SUB_LEARN = "EDIT_SUB_LEARN";
export const DELETE_SUB_LEARN = "DELETE_SUB_LEARN";
export const ADD_QUESTIONNAIRE = "ADD_QUESTIONNAIRE";
export const EDIT_QUESTIONNAIRE = "EDIT_QUESTIONNAIRE";
export const DELETE_QUESTIONNAIRE = "DELETE_QUESTIONNAIRE";

export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY";
export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";

export const GET_VENDOR = "GET_VENDOR";
export const ADD_VENDOR = "ADD_VENDOR";
export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";

export const GET_PACKAGE_TYPE = "GET_PACKAGE_TYPE";
export const ADD_PACKAGE_TYPE = "ADD_PACKAGE_TYPE";
export const UPDATE_PACKAGE_TYPE = "UPDATE_PACKAGE_TYPE";
export const DELETE_PACKAGE_TYPE = "DELETE_PACKAGE_TYPE";

export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const GET_ATTRIBUTES = "GET_ATTRIBUTES";
export const GET_ATTRIBUTE_TERMS = "GET_ATTRIBUTE_TERMS";
export const UPDATE_ATTRIBUTE = "UPDATE_ATTRIBUTE";
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SUBSCRIBED_PRODUCTS = "GET_SUBSCRIBED_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_COMBO = "ADD_COMBO";
export const GET_COMBOS = "GET_COMBOS";
export const UPDATE_COMBO = "UPDATE_COMBO";
export const DELETE_COMBO = "DELETE_COMBO";

export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const GET_REVIEWS = "GET_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";

export const ADD_COUPON = "ADD_COUPON";
export const GET_COUPONS = "GET_COUPONS";
export const DELETE_COUPON = "DELETE_COUPON";

export const GET_WISHLISTS = "GET_WISHLISTS";
export const DELETE_WISHLIST = "DELETE_WISHLIST";

export const GET_AMBASSADORS = "GET_AMBASSADORS";
export const ADD_AMBASSADOR = "ADD_AMBASSADOR";
export const UPDATE_AMBASSADOR = "UPDATE_AMBASSADOR";
export const DELETE_AMBASSADOR = "DELETE_AMBASSADOR";

export const ADD_CREATIVE = "ADD_CREATIVE";
export const GET_CREATIVES = "GET_CREATIVES";
export const DELETE_CREATIVE = "DELETE_CREATIVE";
export const GET_LEAD_LIST = "GET_LEAD_LIST";
