import {
  faMedium,
  faCreativeCommonsShare,
  faWpforms,
  faAffiliatetheme,
} from "@fortawesome/free-brands-svg-icons";
import {
  faList,
  faUserTie,
  faBoxOpen,
  faHome,
  faShoppingCart,
  faPenAlt,
  faTags,
  faUsers,
  faInfoCircle,
  faImage,
  faCalculator,
  faHandsHelping,
  faUserCog,
  faAngleDoubleRight,
  faShoppingBasket,
  faColumns,
} from "@fortawesome/free-solid-svg-icons";
// import {  } from '@fortawesome/free-regular-svg-icons'

export default {
  items: [
    {
      id: "navigation",
      title: "Navigation",
      type: "group",
      icon: "icon-navigation",
      children: [
        {
          id: "dashboard",
          title: "Dashboard",
          type: "item",
          url: "/dashboard/default",
          icon: faHome,
        },
      ],
    },

    {
      id: "pages",
      title: "Pages",
      type: "group",
      icon: "icon-pages",
      children: [
        // {
        // 	id: "auth",
        // 	title: "Authentication",
        // 	type: "collapse",
        // 	icon: "feather icon-lock",
        // 	badge: {
        // 		title: "New",
        // 		type: "label-danger",
        // 	},
        // 	children: [
        // 		{
        // 			id: "signup-1",
        // 			title: "Sign up",
        // 			type: "item",
        // 			url: "/auth/signup",
        // 			target: true,
        // 			breadcrumbs: false,
        // 		},
        // 		{
        // 			id: "signin-1",
        // 			title: "Sign in",
        // 			type: "item",
        // 			url: "/auth/signin",
        // 			target: true,
        // 			breadcrumbs: false,
        // 		},
        // 	],
        // },
        {
          id: "Blog",
          title: "Blog",
          type: "item",
          url: "/Blog",
          classes: "nav-item",
          icon: faMedium,
        },
        {
          id: "Product Category",
          title: "Category",
          type: "item",
          url: "/ProductCategory",
          classes: "nav-item",
          icon: faList,
        },
        {
          id: "Vendor",
          title: "Vendor",
          type: "item",
          url: "/Vendor",
          classes: "nav-item",
          icon: faUserTie,
        },
        {
          id: "PackageType",
          title: "Package Type",
          type: "item",
          url: "/PackageType",
          classes: "nav-item",
          icon: faBoxOpen,
        },
        {
          id: "Products",
          title: "Products",
          type: "collapse",
          icon: faShoppingCart,
          children: [
            {
              id: "Attribute",
              title: "Attribute",
              type: "item",
              url: "/Attribute",
              classes: "nav-item",
              icon: faAngleDoubleRight,
            },
            {
              id: "Product List",
              title: "Product List",
              type: "item",
              url: "/ProductList",
              classes: "nav-item",
              icon: faShoppingBasket,
            },
            {
              id: "Combo List",
              title: "Combo List",
              type: "item",
              url: "/ComboList",
              classes: "nav-item",
              icon: faShoppingBasket,
            },
            {
              id: "Product Form",
              title: "Add Product",
              type: "item",
              url: "/ProductForm/add",
              classes: "nav-item",
              icon: faWpforms,
            },
            {
              id: "Combo Form",
              title: "Add Combo",
              type: "item",
              url: "/ComboForm/add",
              classes: "nav-item",
              icon: faWpforms,
            },
          ],
        },
        {
          id: "Review",
          title: "Reviews",
          type: "item",
          url: "/Review",
          classes: "nav-item",
          icon: faPenAlt,
        },
        {
          id: "Coupon",
          title: "Coupons",
          type: "item",
          url: "/Coupon",
          classes: "nav-item",
          icon: faTags,
        },
        {
          id: "Users",
          title: "Users",
          type: "item",
          url: "/Users",
          classes: "nav-item",
          icon: faUsers,
        },
        {
          id: "SubscribedProduct",
          title: "Subscribed Products",
          type: "item",
          url: "/SubscribedProducts",
          classes: "nav-item",
          icon: faShoppingCart,
        },
        {
          id: "Wishlist",
          title: "Wishlist",
          type: "item",
          url: "/Wishlist",
          classes: "nav-item",
          icon: faList,
        },
        {
          id: "Affiliation",
          title: "Affiliation",
          type: "collapse",
          icon: faAffiliatetheme,
          children: [
            {
              id: "Statistics",
              title: "Statistics",
              type: "item",
              url: "/Statistics",
              classes: "nav-item",
              icon: faCalculator,
            },
            {
              id: "Ambassador Management",
              title: "Ambassador Management",
              type: "item",
              url: "/AmbassadorManagement",
              classes: "nav-item",
              icon: faUserCog,
            },
            {
              id: "Referral",
              title: "Referrals",
              type: "item",
              url: "/Referrals",
              classes: "nav-item",
              icon: faHandsHelping,
            },
            {
              id: "Creatives",
              title: "Creatives",
              type: "item",
              url: "/Creatives",
              classes: "nav-item",
              icon: faCreativeCommonsShare,
            },
          ],
        },
        {
          id: "Orders",
          title: "Orders",
          type: "item",
          url: "/Orders",
          classes: "nav-item",
          icon: faShoppingBasket,
        },
        {
          id: "FooterMenu",
          title: "Footer Menus",
          type: "item",
          url: "/FooterMenu",
          classes: "nav-item",
          icon: faList,
        },
        {
          id: "Site-content",
          title: "Site Content",
          type: "collapse",
          icon: faColumns,
          // badge: {
          // 	title: "New",
          // 	type: "label-danger",
          // },
          children: [
            {
              id: "Home",
              title: "Home",
              type: "item",
              url: "/Home",
              classes: "nav-item",
              icon: faHome,
            },
            {
              id: "Shop",
              title: "Shop",
              type: "item",
              url: "/Shop",
              classes: "nav-item",
              icon: faShoppingCart,
            },
            {
              id: "Category",
              title: "Category",
              type: "item",
              url: "/Category",
              classes: "nav-item",
              icon: faList,
            },
            {
              id: "Banner",
              title: "Banner",
              type: "item",
              url: "/Banner",
              classes: "nav-item",
              icon: faImage,
            },
            {
              id: "Learn",
              title: "Learn",
              type: "item",
              url: "/Learn",
              classes: "nav-item",
              icon: faInfoCircle,
            },
          ],
        },

        // {
        // 	id: "menu-level",
        // 	title: "Menu Levels",
        // 	type: "collapse",
        // 	icon: "feather icon-menu",
        // 	children: [
        // 		{
        // 			id: "menu-level-1.1",
        // 			title: "Menu Level 1.1",
        // 			type: "item",
        // 			url: "#!",
        // 		},
        // 		{
        // 			id: "menu-level-1.2",
        // 			title: "Menu Level 2.2",
        // 			type: "collapse",
        // 			children: [
        // 				{
        // 					id: "menu-level-2.1",
        // 					title: "Menu Level 2.1",
        // 					type: "item",
        // 					url: "#",
        // 				},
        // 				{
        // 					id: "menu-level-2.2",
        // 					title: "Menu Level 2.2",
        // 					type: "collapse",
        // 					children: [
        // 						{
        // 							id: "menu-level-3.1",
        // 							title: "Menu Level 3.1",
        // 							type: "item",
        // 							url: "#",
        // 						},
        // 						{
        // 							id: "menu-level-3.2",
        // 							title: "Menu Level 3.2",
        // 							type: "item",
        // 							url: "#",
        // 						},
        // 					],
        // 				},
        // 			],
        // 		},
        // 	],
        // },
        // {
        // 	id: "disabled-menu",
        // 	title: "Disabled Menu",
        // 	type: "item",
        // 	url: "#",
        // 	classes: "nav-item disabled",
        // 	icon: "feather icon-power",
        // },
        /*{
                    id: 'buy-now',
                    title: 'Buy Now',
                    type: 'item',
                    icon: 'feather icon-user',
                    classes: 'nav-item',
                    url: 'https://codedthemes.com',
                    target: true,
                    external: true,
                    badge: {
                        title: 'v1.0',
                        type: 'label-primary'
                    }
                }*/
      ],
    },
  ],
};
